sudo: required
services:
  - docker

before_install:
  - docker build -t hormetix/docker-react3 -f Dockerfile.dev .

script:
  - docker run -e CI=true hormetix/docker-react3 npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react3"
  env: "Dockerreact3-env"
  bucker_name: "docker-react3"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"